### ISSUE TITLE
阿里巴巴工作机会

### ISSUE THREAD

**Issue by bigfactory** [sheguloves/sheguloves.github.io#1]
阿里巴巴前端工程师岗位考虑吗，工作地点：杭州/深圳

**Comment by sheguloves** [comment]
@bigfactory 考虑的，有没有具体的JD

**Comment by bigfactory** [comment]
https://job.alibaba.com/zhaopin/position_detail.htm?positionId=26056

简历可以发我邮箱xiaocong.hxc@alibaba-inc.com
